version: "3.7"

services:
  flask:
    build: ./flask
    container_name: flask
    restart: always
    environment:
      - APP_NAME=MyFlaskApp
    expose:
      - 8080 # Exposes this port purely to containers, not outside the docker network

  nginx:
    build: ./nginx
    container_name: nginx
    restart: always
    ports:
      - 80:80
